### ISSUE TITLE
[Breaking Change] With 4.0 breaking changes in template name

### ISSUE THREAD

**Issue by bh-teufels** [buepro/typo3-container_elements#10]
With the new version 4.0 the template name changes from <...>.html to Ce<...>.html e.g. Container.html to CeContainer.html
so in every project where a template has been overwritten now has to be adapt.

ist it possible that you could make a fallback for the old template names? 

like 
tt_content.ce_container.templateName. 10 = CeContainer
tt_content.ce_container.templateName. 20 = Container

**Comment by buepro** [comment]
Unfortunately this doesn't work... Most likely it would need to be achieved with a user function checking all the template paths for an existing template:

`tt_content.ce_container.templateName.preUserFunc = Vendor\SitePackage\UserFunction\TemplateUserFunction->resolveTemplate`

This should be accommodated in site packages that need to provide the backward compatibility.

Please reopen the ticket to continue this thread.
