### ISSUE TITLE
[Bug] CE position move (BE) not possible anymore

### ISSUE THREAD

**Issue by bh-teufels** [buepro/typo3-container_elements#12]
no matter where CE placed or moved to after "reload" site always on first position
no errors or log entry that could point to the reason of this behavior

Typo3: 11.5.14
PHP: 7.4 & 8.1
container_elements: 4.0.0 & main (6a688ce)

only appears on container_elements v4 
with 3.* it is working

**Comment by buepro** [comment]
I can't reproduce it... not in development nor in production environment. Do you have as well container 2.0.1 installed and do you observe the issue on a fresh installation or when updating an existing one?

**Comment by bh-teufels** [comment]
updating existing one 
container ist on version 2.0.1

i will try it on a blank new installation

**Comment by buepro** [comment]
Could you try to run `./vendor/bin/typo3cms container:sorting --apply` as described in the [container release 2.0.0](https://github.com/b13/container/releases/tag/2.0.0)? Using the upgrade wizard in the BE might not work reliably. NOTE: The mentioned command might be needed to be run several times.

**Comment by bh-teufels** [comment]
it's a very weird behaviour. 

With only new Created Elements there is no problem they could be moved 
but could not moved (down) between old/existing ones.
Problem only appears on moving Elements down or creating new Elements (v4) between old (v3) ones. Moving up ist working.


(on a new Installation i have only new elements so there is no problem. Problem only maybe with Elements created on version 3 and now be on version 4)

**Comment by bh-teufels** [comment]
run `./vendor/bin/typo3cms container:sorting --apply` multiple times seems to fix the problem. Thank you very much
