### ISSUE TITLE
Migration from flux_elements?

### ISSUE THREAD

**Issue by Inovanet** [buepro/typo3-container_elements#13]
Hello,

I saw that you developed both typo3-flux_elements and typo3-container_elements.
Flux_elements is not supported for TYPO3 11 and I've been looking for a replacement.
Is there a chance for a migration of the extensions?
Looking at the structure some parts seem the same.

**Comment by buepro** [comment]
I don't have it clear... since flux used the colPos field in a special way. As well the flexforms might vary. Would need to be further checked...
