### ISSUE TITLE
TypoScript inclusion not working for 5.0.x version

### ISSUE THREAD

**Issue by instruccionesaldorso** [buepro/typo3-container_elements#14]
This TypoScript block has no usage for 5.0.x version:

https://github.com/buepro/typo3-container_elements/blob/v5.0.0/ext_localconf.php#L27-L43

It should be removed.

And global option "autoLoadStaticTS" as well.

"showDeprecatedItems" global option has no effect, so the whole file ext_conf_template.txt can be removed too.

**Comment by buepro** [comment]
Actually the deprecation rule was wrong, it depends on pizpalue... Thank you for your hint.

**Comment by instruccionesaldorso** [comment]
@buepro I don't get it.
What I meant is: if you load this TypoScript file https://github.com/buepro/typo3-container_elements/blob/v5.0.0/ext_localconf.php#L38 in *version 5.0.0* from the extension, there is no such file. Not even a "Pizpalue" folder.

**Comment by buepro** [comment]
@instruccionesaldorso you're right! This was dropped in #5d594a5b. Thank you again!
