### ISSUE TITLE
After migrating from 4.0.2 to 5.0.0, content is not rendered inside grid areas

### ISSUE THREAD

**Issue by instruccionesaldorso** [buepro/typo3-container_elements#15]
I'm using TYPO3 11.5.26.
After upgrading EXT:container_elements from 4.0.2 to 5.0.0, all my container elements (I got some custom ones) don't display the content inside each column area e.g. a grid of 2 columns with content inside each column doesn't display anything inside the wrappers.

As far as I observed, I think the problem lies here:

```
<f:for each="{content}" as="record">
   {f:cObject(typoscriptObjectPath: 'lib.containerElements.renderContent', data: record)}
</f:for>
```

Even if `{content}` is an array which is filled, somehow this cObject is not rendered.

Could you reproduce this issue? Not sure how to fix it.

**Comment by buepro** [comment]
Thank you for this!

**Comment by instruccionesaldorso** [comment]
@buepro Would you mind making a new release 5.0.1 with this topic? I think it's quite important for the extension to work properly. We're in the middle of a v11 upgrade and we would like to keep this extension to the latest version possible as well.

**Comment by buepro** [comment]
See v5.0.1
