### ISSUE TITLE
Container not opened after insert

### ISSUE THREAD

**Issue by Mordef** [buepro/typo3-container_elements#16]
When insert new Element from Wizard, the Element is open to edit properties.
Container-Elements will not open, they redirect to the Page and I must found the Item to edit it.

Any way to make open for edit after insert?

**Comment by buepro** [comment]
For this you can adjust the TCA configuration property `saveAndCloseInNewContentElementWizard`. You might add the following adjustments to your site package under `Configuration/TCA/Overrides/container_elements.php`:

```
$GLOBALS['TCA']['tt_content']['containerConfiguration']['ce_columns2']['saveAndCloseInNewContentElementWizard'] = 1;
```

**Comment by Mordef** [comment]
Sorry, its for TYPO3 v11.5
`setSaveAndCloseInNewContentElementWizard`: 
```
saveAndClose for new content element wizard (v10 only)
```
So its not working :/
Any other way?

**Comment by buepro** [comment]
I see... then you can configure it using PageTS. To set it for the two columns container you can use the following:
```
mod.wizards.newContentElement.wizardItems.container.elements.ce_columns2.saveAndClose = 0
```

See as well [TSconfig reference](https://docs.typo3.org/m/typo3/reference-tsconfig/12.4/en-us/PageTsconfig/Mod.html#newcontentelement-wizarditems).
