### ISSUE TITLE
Can't insert hidden records in nested columns

### ISSUE THREAD

**Issue by Inovanet** [buepro/typo3-container_elements#18]
When trying to drop a hidden record into a nested column, the record is dropped to the previous position instead to the new one.
If the record is active, everything works fine.

System:
TYPO3 11.5.18
PHP 7.4
container_elements 4.0.1

**Comment by buepro** [comment]
On my test system with TYPO3 v11.5.27, container_elements v4.0.2 and container v2.2.2 the behavior can't be reproduced. Could you try to update these extensions? Note: The backend functionality is mainly given by the extension container.
