### ISSUE TITLE
Columns without content are nor rendered

### ISSUE THREAD

**Issue by nannione** [buepro/typo3-container_elements#20]
Hello,
i noticed that if i do not place any content element in a column, the column will not be rendered in the frontend. Is this intentional or do i miss something here? I often use empty columns to create horizontal space in layouts.

**Comment by buepro** [comment]
The empty column isn't rendered since columns can have an offset (see [Bootstrap-OffsettingColumns](https://getbootstrap.com/docs/5.3/layout/columns/#offsetting-columns)). Would you still need the feature to get empty columns rendered?

**Comment by nannione** [comment]
I think yes, otherwise i need to expect that the editors know the offset class name, which is usually not the case. I can imagine adding a selector with offset classes next to column class fields and/or a global setting which sets the render type for empty columns.

**Comment by buepro** [comment]
Good point! I'll add the feature on the next occasion.
