### ISSUE TITLE
Too few arguments DataHandlerHook.php on line 71

### ISSUE THREAD

**Issue by slowhand11** [buepro/typo3-container_elements#23]
Too few arguments to function TYPO3\CMS\Backend\Form\FormDataCompiler::compile(), 1 passed in /html/typo3-composer/vendor/buepro/typo3-container-elements/Classes/Hooks/DataHandlerHook.php on line 71 and exactly 2 expected

T3 13.4.0 composer based

**Comment by ivanbilj** [comment]
Fighting with the same problem here for some days.
TYPO3 13.4.0 non-composer
MySQL 10.6.18-MariaDB-cll-lve-log

**Comment by ivanbilj** [comment]
If I read: 
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.4/Deprecation-100581-AvoidConstructorArgumentInFormDataCompiler.html

Then lines 71 and 72 should be left out?
If I uncomment them it seems to work /so far).

**Comment by slowhand11** [comment]
You are right, ive misunderstood that.

**Comment by buepro** [comment]
@slowhand11, @ivanbilj : Thank you for sharing your findings!
