### ISSUE TITLE
Too few arguments DataHandlerHook.php on line 71 - follow up

### ISSUE THREAD

**Issue by ivanbilj** [buepro/typo3-container_elements#24]
Out of the blue I run into following error (after the the seemingly successful changes 4 days ago).

 
![Screenshot from 2024-11-02 16-19-16](https://github.com/user-attachments/assets/de9e24b4-ad68-4862-be79-4d0e9ba329b7)

As mentioned earlier by slowhand11 here:
https://github.com/buepro/typo3-container_elements/issues/23#issuecomment-2442382646

**Comment by buepro** [comment]
@ivanbilj Thank you!
