### ISSUE TITLE
Card element does not show the optional Content nor Image content

### ISSUE THREAD

**Issue by ivanbilj** [buepro/typo3-container_elements#28]
In version 6.0.2 the Card element does not work.
The screenshots will explain:

![v12 vs v13](https://github.com/user-attachments/assets/cb6c24d6-6b6e-4e77-9c50-d273693b0372)

**Comment by ivanbilj** [comment]
I corrected the Namespace definitions. The cards work.
 (Have to add  to: 
 .card-img, .card-img-top, .card-img-bottom {
  height: auto;
}

Question: As the v13 back-end still shows as in the upper screenshot (at the right), is this how it is meant to be??

**Comment by buepro** [comment]
Thank you for reporting! This certainly is a bug and I try to address it asap.
