### ISSUE TITLE
Nesting elements - after resolving issue #28

### ISSUE THREAD

**Issue by ivanbilj** [buepro/typo3-container_elements#29]
Trying to place an accordion, card etc. in a grid or column results in error.
F.e.: try to place a 2 column element and place a card into a column.
A workaround for the moment is to place a column and a, separate, card and drag and drop the card into a column.

![Screenshot from 2024-12-06 17-19-51](https://github.com/user-attachments/assets/046b7ae9-c55d-4a28-b0fe-04aa1f2a9106)

Thank you very much for resolving #28 !!!

**Comment by buepro** [comment]
Thank you again for reporting. Could you check if it is fine know?

**Comment by ivanbilj** [comment]
Works like a charm!!
Thank you very, very much indeed.
