### ISSUE TITLE
Error on Columns (TYPO3Fluid\Fluid\Core\ViewHelper\Exception Unsupported input type; cannot convert to array!)

### ISSUE THREAD

**Issue by bh-teufels** [buepro/typo3-container_elements#3]
if i use 2/3/4-Columns i get the error

TYPO3Fluid\Fluid\Core\ViewHelper\Exception
Unsupported input type; cannot convert to array!

causes by 
{v:iterator.merge(a: settings.containerElements, b: data.pi_flexform, useKeys: 1) -> v:variable.set(name: 'settings.containerElements')}
in web/typo3conf/ext/container_elements/Resources/Private/Partials/General/Columns.html

-> getting no Errors if i remove this line

My System:
PHP 7.4
Typo3 10.4.16

**Comment by buepro** [comment]
This is solved in v2.1.1. Thank you for reporting.
