### ISSUE TITLE
Different widths for different breakpoints

### ISSUE THREAD

**Issue by klodeckl** [buepro/typo3-container_elements#7]
Hello,

I will switch from bootstrap_grids (based on gridelements) to container_elements. bootstrap_grids had the option to define widths for each breakpoint. How about adding this options? I attached a screenshot here.
<img width="790" alt="Bildschirmfoto 2021-12-05 um 00 07 39" src="https://user-images.githubusercontent.com/510262/144727372-dec702b8-f2a1-450d-8dc6-a7ae680804d0.png">
.

**Comment by buepro** [comment]
Thank you for your input. To implement a mode selector with the items `One breakpoint` and `All breakpoints` could be added. With `One breakpoint` the current form and with `All breakpoints` the form as known from bootstrap_grids would be shown. Do you have possibility to put hands on?

**Comment by klodeckl** [comment]
One breakpoint and All breakpoints is a good starting point. But I’m thinking about to get all the possibilities selectable the bootstrap grid layout offers (maybe everything is not possible because it gets too difficult for the editor to understand). E.g. how about „row columns“ (https://getbootstrap.com/docs/5.1/layout/grid/#row-columns) or nesting.

And what do you think about another content element with the number of columns selectable (5 or more)? I already hat that use case in the passt a few times.

Currently I don’t have time to put hands on, but I think maybe in january (assuming I am able to).

**Comment by buepro** [comment]
The latest release v3.1.0 contains a grid element that covers as well use cases where more than three columns need to be rendered. Do you still think that the flex forms for column elements should be enhanced?
