### ISSUE TITLE
Bug in combination with tx_news

### ISSUE THREAD

**Issue by jochenkruempelmann** [buepro/typo3-container_elements#8]
Hi,

I've noticed something strange: if i use container_elements in Typo3 v11.5.5 in combination with tx_news, the category tree in the news plugin is hidden. As soon as I deactivate container_elements in the extension manager the tree is shown. It happens in different installations of Typo3 v 11.5.5 and as far as I can tell container_elements is responsible for this behaviour.

Thanks in advance for any idea to solve this problem

![bug-news](https://user-images.githubusercontent.com/55384087/150535765-b76ee4f9-2abc-4954-b231-238343d5ea28.png)

**Comment by buepro** [comment]
I can't reproduce this behaviour. Do you have gridelements or any other structuring extension installed as well? To find out whether it is related to container_elements or container you could uninstall container_elements and install [container_example](https://github.com/b13/container-example). Then add the news-plugin to a container_example-element.
