### ISSUE TITLE
Bug: Nested accordion elements

### ISSUE THREAD

**Issue by ChristopherSchulz94** [buepro/typo3-container_elements#9]
System:
- TYPO3 version: 11.5.13
- PHP version: 7.4.6
- Extension version: 3.1.0

When I want to nest several accordion elements, there is a problem in the frontend. As soon as I open the first accordion and try to open the second one, the complete second accordion disappears.

**Comment by buepro** [comment]
Thank you for this information. Did you test once if bootstrap supports it?

**Comment by klodeckl** [comment]
Same here. Bootstrap supports it, see: https://codepen.io/WinterSilence/pen/abpopXa?editors=1010
I already had it working with gridelements. It seems to be javascript related?

**Comment by klodeckl** [comment]
When deleting data-bs-parent="#accordion-{data.uid}" from div class="accordion-collapse" it works. But I don’t know why, it should also work with data-bs-parent (see codepen example above). Any idea?
